name: E2E Regression

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 21 * * *'
  workflow_dispatch:

env:
  TARGET: "%regex[.*Tests.*],com.automationexercise.tests.**.**,com.automationexercise.tests.**"

jobs:
  chrome_Linux:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
      - uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.13.0

      - name: Running Tests
        run: mvn -Dtest="${TARGET}" -DexecutionType="localHeadless" -DbrowserType="Chrome"

      - name:  Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Report
          path: 'test-output/reports/*.html'
  Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
      - uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.13.0

      - name: Running Tests
        run: mvn -Dtest="${TARGET}" -DexecutionType="localHeadless" -DbrowserType="Chrome"

      - name:  Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Edge_windows_Report
          path: 'test-output/reports/*.html'
